import type { CourierTemplate } from "../types";

export const COURIER_TEMPLATES: CourierTemplate[] = [
  {
    id: "cj",
    name: "CJ대한통운",
    description: "CJ 택배 일반 업로드 양식",
    color: "#E31837",
    columns: [
      { key: "recipientName", header: "받는분" },
      { key: "recipientMobile", header: "받는분전화" },
      { key: "empty", header: "받는분기타연락처", defaultValue: "" },
      { key: "zipCode", header: "받는분우편번호" },
      { key: "address", header: "받는분주소" },
      { key: "productName", header: "품목명" },
      { key: "quantity", header: "BOX수량", defaultValue: "1" },
      { key: "deliveryMessage", header: "배송메시지" },
      { key: "orderNo", header: "주문번호" },
    ],
  },
  {
    id: "hanjin",
    name: "한진택배",
    description: "한진 택배 업로드 양식",
    color: "#FF6600",
    columns: [
      { key: "recipientName", header: "수하인명" },
      { key: "recipientMobile", header: "수하인전화" },
      { key: "zipCode", header: "수하인우편번호" },
      { key: "address", header: "수하인주소" },
      { key: "productName", header: "품목명" },
      { key: "quantity", header: "포장수", defaultValue: "1" },
      { key: "deliveryMessage", header: "배송메세지" },
      { key: "orderNo", header: "고객주문번호" },
    ],
  },
  {
    id: "lotte",
    name: "롯데택배",
    description: "롯데 택배 업로드 양식",
    color: "#ED1C24",
    columns: [
      { key: "recipientName", header: "받는분성명" },
      { key: "recipientMobile", header: "받는분전화번호" },
      { key: "zipCode", header: "받는분우편번호" },
      { key: "address", header: "받는분주소" },
      { key: "productName", header: "상품명" },
      { key: "quantity", header: "수량", defaultValue: "1" },
      { key: "deliveryMessage", header: "배송메세지" },
      { key: "orderNo", header: "주문번호" },
    ],
  },
  {
    id: "epost",
    name: "우체국택배",
    description: "우체국 택배 업로드 양식",
    color: "#004B98",
    columns: [
      { key: "recipientName", header: "수취인명" },
      { key: "recipientMobile", header: "수취인휴대폰" },
      { key: "zipCode", header: "수취인우편번호" },
      { key: "address", header: "수취인주소" },
      { key: "productName", header: "품명" },
      { key: "quantity", header: "택배수량", defaultValue: "1" },
      { key: "deliveryMessage", header: "배송메시지" },
      { key: "orderNo", header: "주문번호" },
    ],
  },
];
